name: pymare-book
channels:
  - conda-forge
dependencies:
  - python==3.8
  - r-IRkernel
  - r-metadat
  - r-metafor
  - pip
  - pip:
    - jupyter-book
    - jupyter_contrib_core
    - matplotlib
    - rpy2
    - pymare==0.0.4rc2
